import { describe, expect, it } from 'vitest';
import { readFileSync } from 'fs';
import path from 'path';

describe('@0ctx/cli build artifact source', () => {
    it('includes expected command verbs in CLI source', () => {
        const sourcePath = path.resolve(__dirname, '..', 'src', 'index.ts');
        const source = readFileSync(sourcePath, 'utf8');
        const registrySource = readFileSync(path.resolve(__dirname, '..', 'src', 'entry', 'registry.ts'), 'utf8');
        const dispatchSource = readFileSync(path.resolve(__dirname, '..', 'src', 'entry', 'dispatch.ts'), 'utf8');
        const noArgsSource = readFileSync(path.resolve(__dirname, '..', 'src', 'entry', 'no-args.ts'), 'utf8');
        const workstreamSource = readFileSync(path.resolve(__dirname, '..', 'src', 'commands', 'workstream', 'workstreams.ts'), 'utf8');
        const sessionSource = readFileSync(path.resolve(__dirname, '..', 'src', 'commands', 'workstream', 'sessions.ts'), 'utf8');
        const policySource = readFileSync(path.resolve(__dirname, '..', 'src', 'commands', 'product', 'policy', 'data-policy.ts'), 'utf8');
        const repoReadinessDisplaySource = readFileSync(
            path.resolve(__dirname, '..', 'src', 'commands', 'product', 'repo-readiness-display.ts'),
            'utf8'
        );
        const syncSource = readFileSync(path.resolve(__dirname, '..', 'src', 'commands', 'product', 'policy', 'sync.ts'), 'utf8');
        const lifecycleSource = readFileSync(path.resolve(__dirname, '..', 'src', 'commands', 'lifecycle', 'health.ts'), 'utf8');
        const setupSource = readFileSync(path.resolve(__dirname, '..', 'src', 'commands', 'lifecycle', 'setup.ts'), 'utf8');
        const helpSource = readFileSync(path.resolve(__dirname, '..', 'src', 'commands', 'help', 'index.ts'), 'utf8');
        const versionSource = readFileSync(path.resolve(__dirname, '..', 'src', 'commands', 'misc', 'version.ts'), 'utf8');
        const daemonSource = readFileSync(path.resolve(__dirname, '..', 'src', 'cli-core', 'daemon.ts'), 'utf8');
        const platformSource = readFileSync(path.resolve(__dirname, '..', 'src', 'cli-core', 'platform.ts'), 'utf8');
        const clientsSource = readFileSync(path.resolve(__dirname, '..', 'src', 'cli-core', 'clients.ts'), 'utf8');
        const repoSource = readFileSync(path.resolve(__dirname, '..', 'src', 'cli-core', 'repo.ts'), 'utf8');
        const productBootstrapSource = readFileSync(path.resolve(__dirname, '..', 'src', 'commands', 'product', 'bootstrap.ts'), 'utf8');
        const productEnableSource = readFileSync(path.resolve(__dirname, '..', 'src', 'commands', 'product', 'enable.ts'), 'utf8');
        const argsSource = readFileSync(path.resolve(__dirname, '..', 'src', 'cli-core', 'args.ts'), 'utf8');
        const entrySurface = [source, registrySource, dispatchSource, noArgsSource].join('\n');
        const cliSurface = [entrySurface, setupSource, helpSource, repoReadinessDisplaySource].join('\n');
        const productSurface = [productBootstrapSource, productEnableSource].join('\n');

        expect(dispatchSource).toContain("case 'install'");
        expect(dispatchSource).toContain("case 'enable'");
        expect(dispatchSource).toContain("case 'workspaces'");
        expect(dispatchSource).toContain("case 'agent-context'");
        expect(dispatchSource).toContain("case 'data-policy'");
        expect(dispatchSource).toContain("case 'workstreams'");
        expect(dispatchSource).toContain("case 'bootstrap'");
        expect(dispatchSource).toContain("case 'doctor'");
        expect(dispatchSource).toContain("case 'status'");
        expect(dispatchSource).toContain("case 'version'");
        expect(dispatchSource).toContain("case 'mcp'");
        expect(dispatchSource).toContain("case 'recall'");
        expect(dispatchSource).toContain("case 'extract'");
        expect(dispatchSource).toContain("case 'insights'");
        expect(dispatchSource).toContain("case 'repair'");
        expect(dispatchSource).toContain("case 'reset'");
        expect(dispatchSource).toContain("case 'shell'");
        expect(dispatchSource).toContain("case 'release'");
        expect(dispatchSource).toContain("case 'connector'");
        expect(dispatchSource).toContain("case 'hook'");
        expect(dispatchSource).toContain("return deps.commandShell();");
        expect(dispatchSource).toContain("return deps.commandReleasePublish(parsed.flags);");
        expect(cliSurface).toContain("connector register");
        expect(cliSurface).toContain("connector verify");
        expect(cliSurface).toContain("connector run");
        expect(cliSurface).toContain("0ctx shell");
        expect(cliSurface).toContain("0ctx version [--verbose] [--json]");
        expect(cliSurface).toContain("0ctx --version | -v");
        expect(cliSurface).toContain("0ctx                    Auto-enable inside a repo. Outside a repo, show readiness/help.");
        expect(cliSurface).toContain("0ctx enable [--repo-root=<path>] [--name=<workspace>] [--data-policy=<lean|review|debug|shared>] [--json]");
        expect(cliSurface).toContain("[--clients=ga|claude,factory,antigravity]");
        expect(cliSurface).toContain("Daily use:");
        expect(cliSurface).toContain("0ctx help --advanced");
        expect(cliSurface).toContain("Recommended daily flow:");
        expect(cliSurface).toContain("Advanced / machine management:");
        expect(cliSurface).toContain("Capture support:");
        expect(cliSurface).toContain("GA:                    claude, factory, antigravity");
        expect(cliSurface).toContain("Explicit opt-in only:  non-GA integrations stay outside the normal enable path");
        expect(cliSurface).toContain("0ctx connector hook status [--json] [--include-preview]");
        expect(cliSurface).toContain("0ctx recall [--mode=auto|temporal|topic|graph]");
        expect(cliSurface).toContain("[--start] [--json]");
        expect(cliSurface).toContain("0ctx release publish --version vX.Y.Z [--tag latest|next] [--otp 123456] [--dry-run] [--json]");
        expect(cliSurface).toContain("0ctx setup [--clients=ga|claude,factory,antigravity] [--json] [--validate]");
        expect(cliSurface).toContain("[--skip-service] [--skip-bootstrap]");
        expect(cliSurface).toContain("[--hooks-dry-run]");
        expect(cliSurface).toContain("0ctx status [--json] [--compact]");
        expect(cliSurface).toContain("0ctx repair [--clients=...] [--deep] [--json]");
        expect(cliSurface).toContain("0ctx reset [--confirm] [--full] [--json]");
        expect(cliSurface).toContain("0ctx workstreams [--repo-root=<path>] [--limit=100] [--json]");
        expect(cliSurface).toContain("0ctx workstreams current [--repo-root=<path>] [--branch=<name>] [--worktree-path=<path>]");
        expect(cliSurface).toContain("0ctx workstreams compare [--repo-root=<path>] --source=<branch> --target=<branch>");
        expect(cliSurface).toContain("0ctx workspaces compare [--repo-root=<path>|--source-context-id=<id>]");
        expect(cliSurface).toContain("0ctx branches [--repo-root=<path>] [--limit=100] [--json]");
        expect(cliSurface).toContain("0ctx branches compare [--repo-root=<path>] --source=<branch> --target=<branch>");
        expect(cliSurface).toContain("0ctx sessions [--repo-root=<path>] [--branch=<name>] [--session-id=<id>] [--worktree-path=<path>] [--limit=100] [--json]");
        expect(cliSurface).toContain("0ctx checkpoints [list] [--repo-root=<path>] [--branch=<name>] [--worktree-path=<path>] [--limit=100] [--json]");
        expect(cliSurface).toContain("0ctx extract session [--repo-root=<path>] [--session-id=<id>] [--preview] [--keys=key1,key2] [--max-nodes=12] [--json]");
        expect(cliSurface).toContain("0ctx extract checkpoint [--repo-root=<path>] [--checkpoint-id=<id>] [--preview] [--keys=key1,key2] [--max-nodes=12] [--json]");
        expect(cliSurface).toContain("0ctx insights promote --repo-root=<path> --node-id=<id> --target-context-id=<id>");
        expect(cliSurface).toContain("0ctx resume [--repo-root=<path>] [--session-id=<id>] [--json]");
        expect(cliSurface).toContain("0ctx rewind [--repo-root=<path>] [--checkpoint-id=<id>] [--json]");
        expect(cliSurface).toContain("0ctx explain [--repo-root=<path>] [--checkpoint-id=<id>] [--json]");
        expect(cliSurface).toContain("0ctx logs [--no-open] [--snapshot] [--limit=50] [--since-hours=N] [--grep=text] [--errors-only]");
        expect(cliSurface).toContain("0ctx bootstrap [--dry-run] [--clients=ga|claude,antigravity] [--entrypoint=/path/to/mcp-server.js]");
        expect(cliSurface).toContain("[--mcp-profile=all|core|recall|ops] [--json]");
        expect(cliSurface).toContain("0ctx mcp [bootstrap]");
        expect(cliSurface).toContain("0ctx mcp                     Interactive supported-agent retrieval bootstrap");
        expect(cliSurface).toContain("0ctx install [--clients=ga|claude,factory,antigravity] [--json] [--skip-bootstrap] [--mcp-profile=all|core|recall|ops]");
        expect(clientsSource).toContain("export const DEFAULT_MCP_CLIENTS: SupportedClient[] = ['claude', 'antigravity'];");
        expect(registrySource).toContain("const defaultEnableMcpClients: SupportedClient[] = DEFAULT_MCP_CLIENTS;");
        expect(cliSurface).toContain("0ctx connector service install|enable|disable|uninstall|status|start|stop|restart");
        expect(cliSurface).toContain("0ctx connector status [--json]");
        expect(cliSurface).toContain("0ctx connector verify [--json]");
        expect(cliSurface).toContain("0ctx connector register [--force] [--json]");
        expect(cliSurface).toContain("0ctx sync policy get [--repo-root=<path>] [--json]");
        expect(cliSurface).toContain("0ctx data-policy [--repo-root=<path>] [--json]");
        expect(cliSurface).toContain("0ctx data-policy presets [--json]");
        expect(cliSurface).toContain("0ctx data-policy cleanup [--repo-root=<path>] [--json]");
        expect(policySource).toContain("Usage: 0ctx data-policy set [--repo-root=<path>] [--preset=<lean|review|debug|shared>] [--sync-policy=<local_only|metadata_only|full_sync>]");
        expect(policySource).toContain("commandDataPolicyPresets");
        expect(policySource).toContain("commandDataPolicyCleanup");
        expect(policySource).toContain("Preset catalog");
        expect(policySource).toContain("Apply machine presets with: 0ctx data-policy <lean|review|debug> [--repo-root=<path>] [--json]");
        expect(policySource).toContain("Opt a workspace into richer hosted sync with: 0ctx data-policy shared --repo-root=<path> --confirm-full-sync [--json]");
        expect(policySource).toContain("0ctx data-policy <lean|review|debug> [--repo-root=<path>] [--json]");
        expect(policySource).toContain("0ctx data-policy shared --repo-root=<path> --confirm-full-sync [--json]");
        expect(policySource).toContain("formatScopedDataPolicyPresetLabel");
        expect(cliSurface).toContain("Support overrides:");
        expect(cliSurface).toContain("Advanced utilities:");
        expect(cliSurface).toContain("0ctx connector hook install [--clients=ga|claude,factory,antigravity] [--repo-root=<path>] [--global]");
        expect(cliSurface).toContain("Preview integrations stay outside the normal product path and require explicit advanced opt-in.");
        expect(cliSurface).toContain("Preview overrides:");
        expect(cliSurface).toContain("Use --allow-preview only when you explicitly name preview integrations such as codex,cursor,windsurf.");
        expect(cliSurface).toContain("Keep preview installs and preview retrieval out of the normal enable/bootstrap path.");
        expect(cliSurface).not.toContain("Preview integrations: codex, cursor, windsurf (name them explicitly only when you opt in).");
        expect(cliSurface).not.toContain("Preview MCP retrieval also requires --allow-preview.");
        expect(cliSurface).toContain("0ctx connector hook prune [--days=14] [--json]");
        expect(clientsSource).toContain("export const DEFAULT_HOOK_INSTALL_CLIENTS: HookInstallClient[] = ['claude', 'factory', 'antigravity'];");
        expect(cliSurface).toContain("0ctx connector hook prune [--days=14] [--json]");
        expect(cliSurface).toContain("0ctx connector hook session-start --agent=claude|factory|antigravity [--repo-root=<path>]");
        expect(registrySource).toContain("import { createWorkstreamCommands } from '../commands/workstream';");
        expect(registrySource).toContain("import { createPolicyCommands } from '../commands/product/policy';");
        expect(registrySource).toContain("import { createLifecycleCommands } from '../commands/lifecycle';");
        expect(sessionSource).toContain("sendToDaemon('getAgentContextPack'");
        expect(workstreamSource).toContain("sendToDaemon('getWorkstreamBrief'");
        expect(policySource).toContain("sendToDaemon('getDataPolicy'");
        expect(syncSource).toContain("sendToDaemon('syncStatus'");
        expect(lifecycleSource).toContain('async function collectDoctorChecks');
        expect(lifecycleSource).toContain('async function commandRepair');
        expect(noArgsSource).toContain("reason: connectorState ? 'repo_entrypoint' : 'first_run_repo'");
        expect(cliSurface).toContain("0ctx connector hook ingest --agent=claude|factory|antigravity [--repo-root=<path>]");
        expect(cliSurface).not.toContain("Preview replay utilities:");
        expect(cliSurface).not.toContain("Preview-only replay flows stay out of the normal help surface.");
        expect(cliSurface).toContain('0ctx hook install|status|prune|session-start|ingest  Alias for "0ctx connector hook ..."');
        expect(cliSurface).toContain("0ctx connector queue status [--json]");
        expect(cliSurface).toContain("0ctx sync policy get [--repo-root=<path>] [--json]");
        expect(cliSurface).toContain("0ctx sync policy set <local_only|metadata_only|full_sync> [--repo-root=<path>] [--confirm-full-sync] [--json]");
        expect(cliSurface).toContain("0ctx connector queue logs [--limit=50] [--json] [--clear --confirm|--dry-run]");
        expect(cliSurface).toContain("0ctx connector logs [--service|--system] [--no-open] [--snapshot] [--limit=50] [--since-hours=N] [--grep=text] [--errors-only]");
        expect(cliSurface).toContain("0ctx recall feedback --node-id=<id> (--helpful|--not-helpful)");
        expect(cliSurface).toContain("0ctx recall feedback list|stats [--context-id=<id>] [--node-id=<id>] [--helpful|--not-helpful] [--limit=50] [--json]");
        expect(setupSource).toContain("if (Boolean(flags.validate))");
        expect(dispatchSource).toContain("return deps.commandMcp(parsed.subcommand, parsed.flags);");
        expect(productSurface).toContain("const mcpProfile = deps.parseOptionalStringFlag(flags['mcp-profile'] ?? flags.profile) ?? 'core';");
        expect(productSurface).toContain("const requestedDataPolicy = deps.parseOptionalStringFlag(flags['data-policy'] ?? flags.dataPolicy);");
        expect(productSurface).toContain("? 'Applied the default lean data policy for this new workspace.'");
        expect(productSurface).toContain(": 'Normalized the current custom data policy to the lean default.'");
        expect(productSurface).toContain(": `Using the current ${currentPreset} data policy.`");
        expect(cliSurface).toContain("options.formatLabelValue('Ready', repoReadiness.zeroTouchReady ? 'zero-touch for supported agents' : 'needs one-time setup')");
        expect(cliSurface).toContain("...(repoReadiness.nextActionHint ? [options.formatLabelValue('Next step', repoReadiness.nextActionHint)] : [])");
        expect(productSurface).toContain("if (!nextFlags.clients) nextFlags.clients = 'ga';");
        expect(policySource).toContain("sendToDaemon('setDataPolicy'");
        expect(entrySurface).not.toContain("{ value: 'cursor', label: 'Cursor (Preview)' }");
        expect(entrySurface).not.toContain("{ value: 'windsurf', label: 'Windsurf (Preview)' }");
        expect(productSurface).toContain("is deprecated. Use \\`0ctx bootstrap\\` to repair supported-agent retrieval or \\`0ctx setup\\` for advanced machine management.");
        expect(daemonSource).toContain("path.resolve(__dirname, 'daemon.js')");
        expect(daemonSource).toContain("reinstall/repair the CLI package");
        expect(platformSource).toContain("result.status === 'failed'");
        expect(productSurface).toContain("Restart your AI client app so it picks up automatic retrieval config changes.");
        expect(lifecycleSource).toContain("ops_log_writable");
        expect(dispatchSource).toContain("parsed.subcommand === 'service'");
        expect(dispatchSource).toContain("parsed.subcommand === 'queue'");
        expect(dispatchSource).toContain("return deps.commandStatus(parsed.flags);");
        expect(dispatchSource).toContain("return deps.commandRecall(parsed.flags, parsed.positionalArgs);");
        expect(dispatchSource).toContain("return deps.commandBranches(parsed.positionalArgs, parsed.flags);");
        expect(argsSource).toContain("if (normalized === 'log') return 'logs';");
        expect(versionSource).toContain("console.log(`cli_path: ${payload.cliPath}`);");
        expect(repoSource).toContain("function findGitRepoRoot(input: string | null): string | null {");
        expect(noArgsSource).toContain("Detected git repo. Enabling 0ctx for");
        expect(noArgsSource).toContain("0ctx works repo-first. Move into a project repo and run `0ctx enable`.");
        expect(dispatchSource).toContain("Hosted docs and install guidance live on 0ctx.com.");
    });
});


