import { describe, expect, it } from 'vitest';
import { readFileSync } from 'fs';
import path from 'path';

describe('@0ctx/cli build artifact source', () => {
    it('includes expected command verbs in CLI source', () => {
        const sourcePath = path.resolve(__dirname, '..', 'src', 'index.ts');
        const source = readFileSync(sourcePath, 'utf8');
        const workstreamSource = readFileSync(path.resolve(__dirname, '..', 'src', 'commands', 'workstream', 'workstreams.ts'), 'utf8');
        const sessionSource = readFileSync(path.resolve(__dirname, '..', 'src', 'commands', 'workstream', 'sessions.ts'), 'utf8');
        const policySource = readFileSync(path.resolve(__dirname, '..', 'src', 'commands', 'product', 'policy', 'data-policy.ts'), 'utf8');
        const syncSource = readFileSync(path.resolve(__dirname, '..', 'src', 'commands', 'product', 'policy', 'sync.ts'), 'utf8');
        const lifecycleSource = readFileSync(path.resolve(__dirname, '..', 'src', 'commands', 'lifecycle', 'health.ts'), 'utf8');
        const setupSource = readFileSync(path.resolve(__dirname, '..', 'src', 'commands', 'lifecycle', 'setup.ts'), 'utf8');
        const helpSource = readFileSync(path.resolve(__dirname, '..', 'src', 'commands', 'help', 'index.ts'), 'utf8');
        const versionSource = readFileSync(path.resolve(__dirname, '..', 'src', 'commands', 'misc', 'version.ts'), 'utf8');
        const daemonSource = readFileSync(path.resolve(__dirname, '..', 'src', 'cli-core', 'daemon.ts'), 'utf8');
        const platformSource = readFileSync(path.resolve(__dirname, '..', 'src', 'cli-core', 'platform.ts'), 'utf8');
        const clientsSource = readFileSync(path.resolve(__dirname, '..', 'src', 'cli-core', 'clients.ts'), 'utf8');
        const repoSource = readFileSync(path.resolve(__dirname, '..', 'src', 'cli-core', 'repo.ts'), 'utf8');
        const productBootstrapSource = readFileSync(path.resolve(__dirname, '..', 'src', 'commands', 'product', 'bootstrap.ts'), 'utf8');
        const productEnableSource = readFileSync(path.resolve(__dirname, '..', 'src', 'commands', 'product', 'enable.ts'), 'utf8');
        const argsSource = readFileSync(path.resolve(__dirname, '..', 'src', 'cli-core', 'args.ts'), 'utf8');
        const cliSurface = [source, setupSource, helpSource].join('\n');
        const productSurface = [productBootstrapSource, productEnableSource].join('\n');

        expect(source).toContain("case 'install'");
        expect(source).toContain("case 'enable'");
        expect(source).toContain("case 'workspaces'");
        expect(source).toContain("case 'agent-context'");
        expect(source).toContain("case 'data-policy'");
        expect(source).toContain("case 'workstreams'");
        expect(source).toContain("case 'bootstrap'");
        expect(source).toContain("case 'doctor'");
        expect(source).toContain("case 'status'");
        expect(source).toContain("case 'version'");
        expect(source).toContain("case 'mcp'");
        expect(source).toContain("case 'recall'");
        expect(source).toContain("case 'extract'");
        expect(source).toContain("case 'insights'");
        expect(source).toContain("case 'repair'");
        expect(source).toContain("case 'reset'");
        expect(source).toContain("case 'shell'");
        expect(source).toContain("case 'release'");
        expect(source).toContain("case 'connector'");
        expect(source).toContain("case 'hook'");
        expect(source).toContain("return commandShell();");
        expect(source).toContain("return commandReleasePublish(parsed.flags);");
        expect(cliSurface).toContain("connector register");
        expect(cliSurface).toContain("connector verify");
        expect(cliSurface).toContain("connector run");
        expect(cliSurface).toContain("0ctx shell");
        expect(cliSurface).toContain("0ctx version [--verbose] [--json]");
        expect(cliSurface).toContain("0ctx --version | -v");
        expect(cliSurface).toContain("0ctx                    Auto-enable inside a repo. Outside a repo, show readiness/help.");
        expect(cliSurface).toContain("0ctx enable [--repo-root=<path>] [--name=<workspace>] [--json]");
        expect(cliSurface).toContain("[--clients=ga|claude,factory,antigravity] [--mcp-clients=none|ga|claude,antigravity]");
        expect(cliSurface).toContain("Daily use:");
        expect(cliSurface).toContain("0ctx help --advanced");
        expect(cliSurface).toContain("Recommended daily flow:");
        expect(cliSurface).toContain("Advanced / machine management:");
        expect(cliSurface).toContain("Capture support:");
        expect(cliSurface).toContain("GA:      claude, factory, antigravity");
        expect(cliSurface).toContain("Preview: available only by explicit opt-in");
        expect(cliSurface).toContain("0ctx recall [--mode=auto|temporal|topic|graph]");
        expect(cliSurface).toContain("[--start] [--json]");
        expect(cliSurface).toContain("0ctx release publish --version vX.Y.Z [--tag latest|next] [--otp 123456] [--dry-run] [--json]");
        expect(cliSurface).toContain("0ctx setup [--clients=ga|<explicit-list>] [--no-open] [--json] [--validate]");
        expect(cliSurface).toContain("[--skip-service] [--skip-bootstrap]");
        expect(cliSurface).toContain("[--dashboard-query[=k=v&...]]");
        expect(cliSurface).toContain("0ctx status [--json] [--compact]");
        expect(cliSurface).toContain("0ctx repair [--clients=...] [--deep] [--json]");
        expect(cliSurface).toContain("0ctx reset [--confirm] [--full] [--include-auth] [--json]");
        expect(cliSurface).toContain("0ctx workstreams [--repo-root=<path>] [--limit=100] [--json]");
        expect(cliSurface).toContain("0ctx workstreams current [--repo-root=<path>] [--branch=<name>] [--worktree-path=<path>]");
        expect(cliSurface).toContain("0ctx workstreams compare [--repo-root=<path>] --source=<branch> --target=<branch>");
        expect(cliSurface).toContain("0ctx workspaces compare [--repo-root=<path>|--source-context-id=<id>]");
        expect(cliSurface).toContain("0ctx branches [--repo-root=<path>] [--limit=100] [--json]");
        expect(cliSurface).toContain("0ctx branches compare [--repo-root=<path>] --source=<branch> --target=<branch>");
        expect(cliSurface).toContain("0ctx sessions [--repo-root=<path>] [--branch=<name>] [--session-id=<id>] [--worktree-path=<path>] [--limit=100] [--json]");
        expect(cliSurface).toContain("0ctx checkpoints [list] [--repo-root=<path>] [--branch=<name>] [--worktree-path=<path>] [--limit=100] [--json]");
        expect(cliSurface).toContain("0ctx extract session [--repo-root=<path>] [--session-id=<id>] [--preview] [--keys=key1,key2] [--max-nodes=12] [--json]");
        expect(cliSurface).toContain("0ctx extract checkpoint [--repo-root=<path>] [--checkpoint-id=<id>] [--preview] [--keys=key1,key2] [--max-nodes=12] [--json]");
        expect(cliSurface).toContain("0ctx insights promote --repo-root=<path> --node-id=<id> --target-context-id=<id>");
        expect(cliSurface).toContain("0ctx resume [--repo-root=<path>] [--session-id=<id>] [--json]");
        expect(cliSurface).toContain("0ctx rewind [--repo-root=<path>] [--checkpoint-id=<id>] [--json]");
        expect(cliSurface).toContain("0ctx explain [--repo-root=<path>] [--checkpoint-id=<id>] [--json]");
        expect(cliSurface).toContain("0ctx logs [--no-open] [--snapshot] [--limit=50] [--since-hours=N] [--grep=text] [--errors-only]");
        expect(cliSurface).toContain("0ctx bootstrap [--dry-run] [--clients=ga|<explicit-list>] [--entrypoint=/path/to/mcp-server.js]");
        expect(cliSurface).toContain("[--mcp-profile=all|core|recall|ops] [--json]");
        expect(cliSurface).toContain("0ctx mcp [bootstrap]");
        expect(cliSurface).toContain("0ctx mcp                     Interactive MCP bootstrap for GA clients");
        expect(cliSurface).toContain("0ctx install [--clients=ga|<explicit-list>] [--json] [--skip-bootstrap] [--mcp-profile=all|core|recall|ops]");
        expect(clientsSource).toContain("export const DEFAULT_MCP_CLIENTS: SupportedClient[] = ['claude', 'antigravity'];");
        expect(source).toContain("const DEFAULT_ENABLE_MCP_CLIENTS: SupportedClient[] = DEFAULT_MCP_CLIENTS;");
        expect(cliSurface).toContain("0ctx connector service install|enable|disable|uninstall|status|start|stop|restart");
        expect(cliSurface).toContain("0ctx connector status [--json] [--cloud] [--require-bridge]");
        expect(cliSurface).toContain("0ctx connector verify [--require-cloud] [--json]");
        expect(cliSurface).toContain("0ctx connector register [--force] [--local-only] [--require-cloud] [--json]");
        expect(cliSurface).toContain("0ctx sync policy get [--repo-root=<path>] [--json]");
        expect(cliSurface).toContain("0ctx data-policy [--repo-root=<path>] [--json]");
        expect(cliSurface).toContain("0ctx data-policy set [--repo-root=<path>] [--sync-policy=<local_only|metadata_only|full_sync>]");
        expect(cliSurface).toContain("capture.retentionDays, capture.debugRetentionDays, capture.debugArtifacts,");
        expect(cliSurface).toContain("Support overrides:");
        expect(cliSurface).toContain("Advanced utilities:");
        expect(cliSurface).toContain("0ctx connector hook install [--clients=ga|<explicit-list>] [--repo-root=<path>] [--global]");
        expect(cliSurface).toContain("Preview integrations must be named explicitly when you opt into them.");
        expect(cliSurface).toContain("Example: --clients=codex or --clients=cursor,windsurf");
        expect(cliSurface).toContain("0ctx connector hook prune [--days=14] [--json]");
        expect(clientsSource).toContain("export const DEFAULT_HOOK_INSTALL_CLIENTS: HookInstallClient[] = ['claude', 'factory', 'antigravity'];");
        expect(cliSurface).toContain("0ctx connector hook status [--json]");
        expect(cliSurface).toContain("0ctx connector hook prune [--days=14] [--json]");
        expect(cliSurface).toContain("0ctx connector hook session-start --agent=claude|factory|antigravity [--repo-root=<path>]");
        expect(source).toContain("import { createWorkstreamCommands } from './commands/workstream';");
        expect(source).toContain("import { createPolicyCommands } from './commands/product/policy';");
        expect(source).toContain("import { createLifecycleCommands } from './commands/lifecycle';");
        expect(sessionSource).toContain("sendToDaemon('getAgentContextPack'");
        expect(workstreamSource).toContain("sendToDaemon('getWorkstreamBrief'");
        expect(policySource).toContain("sendToDaemon('getDataPolicy'");
        expect(syncSource).toContain("sendToDaemon('syncStatus'");
        expect(lifecycleSource).toContain('async function collectDoctorChecks');
        expect(lifecycleSource).toContain('async function commandRepair');
        expect(source).toContain("reason: 'repo_entrypoint'");
        expect(source).toContain("'cli.workstreams.current'");
        expect(cliSurface).toContain("0ctx connector hook ingest --agent=claude|windsurf|codex|cursor|factory|antigravity [--repo-root=<path>]");
        expect(cliSurface).toContain('0ctx hook install|status|prune|session-start|ingest  Alias for "0ctx connector hook ..."');
        expect(cliSurface).toContain("0ctx connector queue status [--json]");
        expect(cliSurface).toContain("0ctx sync policy get [--repo-root=<path>] [--json]");
        expect(cliSurface).toContain("0ctx sync policy set <local_only|metadata_only|full_sync> [--repo-root=<path>] [--json]");
        expect(cliSurface).toContain("0ctx connector queue drain [--max-batches=10] [--batch-size=200] [--wait] [--strict|--fail-on-retry] [--timeout-ms=120000] [--poll-ms=1000] [--json]");
        expect(cliSurface).toContain("0ctx connector queue logs [--limit=50] [--json] [--clear --confirm|--dry-run]");
        expect(cliSurface).toContain("0ctx connector logs [--service|--system] [--no-open] [--snapshot] [--limit=50] [--since-hours=N] [--grep=text] [--errors-only]");
        expect(cliSurface).toContain("0ctx recall feedback --node-id=<id> (--helpful|--not-helpful)");
        expect(cliSurface).toContain("0ctx recall feedback list|stats [--context-id=<id>] [--node-id=<id>] [--helpful|--not-helpful] [--limit=50] [--json]");
        expect(setupSource).toContain("if (Boolean(flags.validate))");
        expect(source).toContain("return commandMcp(parsed.subcommand, parsed.flags);");
        expect(productSurface).toContain("const mcpProfile = deps.parseOptionalStringFlag(flags['mcp-profile'] ?? flags.profile) ?? 'core';");
        expect(productSurface).toContain("if (!nextFlags.clients) nextFlags.clients = 'ga';");
        expect(policySource).toContain("sendToDaemon('setDataPolicy'");
        expect(source).not.toContain("{ value: 'cursor', label: 'Cursor (Preview)' }");
        expect(source).not.toContain("{ value: 'windsurf', label: 'Windsurf (Preview)' }");
        expect(productSurface).toContain("is deprecated. Use \\`0ctx bootstrap\\` for MCP registration or \\`0ctx setup\\` for advanced machine management.");
        expect(daemonSource).toContain("path.resolve(__dirname, 'daemon.js')");
        expect(daemonSource).toContain("reinstall/repair the CLI package");
        expect(platformSource).toContain("result.status === 'failed'");
        expect(productSurface).toContain("Restart your AI client app so it reloads MCP config changes.");
        expect(lifecycleSource).toContain("ops_log_writable");
        expect(source).toContain("parsed.subcommand === 'service'");
        expect(source).toContain("parsed.subcommand === 'queue'");
        expect(source).toContain("return commandStatus(parsed.flags);");
        expect(source).toContain("return commandRecall(parsed.flags, parsed.positionalArgs);");
        expect(source).toContain("return commandBranches(parsed.positionalArgs, parsed.flags);");
        expect(argsSource).toContain("if (normalized === 'log') return 'logs';");
        expect(versionSource).toContain("console.log(`cli_path: ${payload.cliPath}`);");
        expect(repoSource).toContain("function findGitRepoRoot(input: string | null): string | null {");
        expect(source).toContain("Detected git repo. Enabling 0ctx for");
        expect(source).toContain("This repo is not enabled yet. Enabling 0ctx for");
        expect(source).toContain("Daemon is unreachable. Re-enabling 0ctx for");
        expect(source).toContain("Use `0ctx enable` inside a repo for the normal product flow. Use `0ctx dashboard` only for hosted support surfaces.");
    });
});
